version: '3.8'

services:
  customer:
    image: vishalkharade/sprint2:v1
    ports:
    - 8484:8484

  postgres:
    image: postgres:14.5
    ports:
    - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: team4
      POSTGRES_DB: team4db