#!/bin/bash
rm -rf target
mvn package
eval $(minikube -p minikube docker-env)
docker build . -t vishalkharade/sprint2:v1
kubectl delete -f app-deployment.yaml
kubectl apply -f app-deployment.yaml
kubectl delete -f app-service.yaml
kubectl apply -f app-service.yaml

kubectl get deployment
kubectl get svc
kubectl get pods